
menu:
- {lang: en, name: 'Blog', url: 'index.html'}
- {lang: de, name: 'Blog', url: 'index-de.html'}
- {lang: en, name: 'Technology-Map', url: 'techmap.html'}
- {lang: de, name: 'Technologienkarte', url: 'techmap-de.html'}
- {lang: en, name: 'Contact', url: 'contact.html'}
- {lang: de, name: 'Kontakt', url: 'contact-de.html'}

email: inbox@jakobmeier.ch
# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
# social:
# - {icon: 'github',     link: 'https://www.github.com/lenpaul'}
# - {icon: 'twitter',    link: 'https://twitter.com/paululele'}
# - {icon: 'linkedin',   link: 'http://www.linkedin.com/in/lenpaul/'}
# - {icon: 'envelope',   link: 'mailto:l.nguyen.paul@gmail.com'}
# - {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

git_repository_root_url: https://github.com/jakmeier/www.jakobmeier.ch/tree/gh-pages/ 

# Used for jmr-analytics, a sort of minimalistic custom analytics tool. Each page will simulate a click on a link in the form BASEURL{{page.ref}} on each load. This can be used to track viewer statics in a external service.
jmr_analytics_base_url: https://bit.ly/2MAMZt-jmr-analytics-

# Customize site text

TEXTS:
  site:
    home_file:
      en: index.html
      de: index-de.html
    contact_file:
      en: contact.html
      de: contact-de.html
    title:
      en: Jakob's Blog 
      de: Jakobs Blog
    description:
      en: coding for fun and growth
      de: Coden für Spass und Erfahrung
    author:
      en: 'Jakob Meier'
      de: 'Jakob Meier'
  read_more: 
    en: 'Read more'
    de: 'Mehr lesen'
  next_page: 
    en: 'Newer'
    de: 'Nächster Beitrag'
  previous_page: 
    en: 'Older'
    de: 'Vorheriger Beitrag'
  posts: 
    en: 'Posts'
    de: 'Beiträge'
  related_posts: 
    en: 'You may also enjoy:'
    de: 'Ähnliche Beiträge:'
  post_date_prefix: 
    en: 'Written on'
    de: 'Verfasst am'
  post_date_postfix: 
    en: 'by'
    de: 'von'
  en:
    en: 'English'
    de: 'Englisch'
  de: 
    en: 'German'
    de: 'Deutsch'
  less-than-a-minute:
    en: less than 1 minute read
    de: weniger als 1 Minute zum Lesen
  one-minute-read:
    en: 1 minute read
    de: 1 Minute zum Lesen
  minutes-to-read:
    en: minutes read
    de: Minuten zum Lesen
  tech-stack:
    en: Technology Stack
    de: Technologien in diesem Beitrag
  next-in-series:
    en: Next post in series
    de: Nächster Beitrag in dieser Serie
  detectjs:
    en: Please activate Javascript.
    de: Bitte aktiviere Javascript.
  find-articles:
    en: Find articles
    de: Finde Beiträge
  by: 
    en: 'by'
    de: 'von'
